<?php 

namespace App\Modules\ImportPermission\Models;

use App\Libraries\CommonFunction;
use Illuminate\Database\Eloquent\Model;

class ImportPermission extends Model {
    protected $table = 'ip_apps';
    protected $fillable = [
        'id',
        'last_br_yes',
        'ref_app_tracking_no',
        'ref_app_approve_date',
        'manually_approved_br_no',
        'manually_approved_br_date',
        'company_id',
        'app_type_mapping_id',
        'request_initiate',
        'app_type_id',
        'reg_no',
        'company_name',
        'company_name_bn',
        'country_of_origin_id',
        'project_name',
        'organization_type_id',
        'organization_status_id',
        'ownership_status_id',
        'section_id',
        'division_id',
        'group_id',
        'class_id',
        'class_code',
        'sub_class_id',
        'other_sub_class_code',
        'other_sub_class_name',
//        'business_sector_id',
//        'business_sector_others',
//        'business_sub_sector_id',
//        'business_sub_sector_others',
        'major_activities',
        'public_others',
        'public_others_field',
        'ceo_full_name',
        'ceo_dob',
        'ceo_spouse_name',
        'ceo_designation',
        'ceo_country_id',
        'ceo_district_id',
        'ceo_thana_id',
        'ceo_post_code',
        'ceo_address',
        'ceo_telephone_no',
        'ceo_mobile_no',
        'ceo_fax_no',
        'ceo_email',
        'ceo_father_name',
        'ceo_mother_name',
        'ceo_nid',
        'ceo_passport_no',
        'ceo_city',
        'ceo_state',
        'office_division_id',
        'office_district_id',
        'office_thana_id',
        'office_post_office',
        'office_post_code',
        'office_address',
        'office_telephone_no',
        'office_mobile_no',
        'office_fax_no',
        'office_email',
        'factory_district_id',
        'factory_thana_id',
        'factory_post_office',
        'factory_post_code',
        'factory_address',
        'factory_telephone_no',
        'factory_mobile_no',
        'factory_fax_no',
        'factory_email',
        'factory_mouja',
        'project_status_id',
        'commercial_operation_date',
        'local_sales',
        'foreign_sales',
        'total_sales',
        'local_male',
        'local_female',
        'local_total',
        'foreign_male',
        'foreign_female',
        'foreign_total',
        'local_land_ivst',
        'local_building_ivst',
        'local_machinery_ivst',
        'local_others_ivst',
        'local_wc_ivst',
        'total_fixed_ivst_million',
        'total_fixed_ivst',
        'total_working_capital',
        'usd_exchange_rate',
        'total_fee',
        'g_full_name',
        'g_designation',
        'g_signature',
        'finance_src_loc_equity_1',
//        'finance_src_loc_equity_2',
        'finance_src_foreign_equity_1',
//        'finance_src_foreign_equity_2',
        'finance_src_loc_total_equity_1',
        'finance_src_loc_loan_1',
//        'finance_src_loc_loan_2',
        'finance_src_foreign_loan_1',
//        'finance_src_foreign_loan_2',
        'finance_src_total_loan',
        'finance_src_loc_total_financing_m',
        'finance_src_loc_total_financing_1',
        'trade_licence_num',
        'trade_licence_issue_date',
        'trade_licence_issuing_authority',
        'trade_licence_attachment',
        'tin_number',
        'tin_issue_date',
        'tin_file_path',
        'machinery_local_qty',
        'machinery_local_price_bdt',
        'imported_qty',
        'imported_qty_price_bdt',
        'total_machinery_qty',
        'total_machinery_price',
        'local_description',
        'imported_description',
        'accept_terms',
        'company_info_review',
        'promoter_info_review',
        'office_address_review',
        'factory_address_review',
        'project_status_review',
        'production_capacity_review',
        'commercial_operation_review',
        'sales_info_review',
        'manpower_review',
        'investment_review',
        'source_finance_review',
        'utility_service_review',
        'trade_license_review',
        'tin_review',
        'machinery_equipment_review',
        'raw_materials_review',
        'ceo_info_review',
        'director_list_review',
        'imported_machinery_review',
        'local_machinery_review',
        'attachment_review',
        'declaration_review',
        'is_draft',
        'is_approved',
        'is_archive',
        'created_at',
        'created_by',
        'updated_at',
        'updated_by',
        'approved_date',
        'payment_date'
    ];

    public static function boot() {
        parent::boot();
        static::creating(function($post) {
            $post->created_by = CommonFunction::getUserId();
            $post->updated_by = CommonFunction::getUserId();
        });

        static::updating(function($post) {
            $post->updated_by = CommonFunction::getUserId();
        });
    }

}
