<?php

namespace App\Modules\VisaRecommendation\Models;

use App\Libraries\CommonFunction;
use Illuminate\Database\Eloquent\Model;

class VisaRecommendation extends Model {
    protected $table = 'vr_apps';
    protected $fillable = [
        'id',
        'certificate_link',
        'visa_type_id',
        'dept_process_cat_id',
        'agree_with_instruction',
        'visa_purpose_id',
        'visa_purpose_others',
        'mission_country_id',
        'high_commision_id',
        'investor_photo',
        'bida_registration_no',
        'emp_name',
        'emp_designation',
        'brief_job_description',
        'emp_passport_no',
        'emp_personal_no',
        'emp_surname',
        'emp_given_name',
        'pass_issue_date',
        'place_of_issue',
        'pass_expiry_date',
        'emp_date_of_birth',
        'emp_place_of_birth',
        'emp_nationality_id',
        'office_division_id',
        'office_district_id',
        'office_thana_id',
        'office_post_office',
        'office_post_code',
        'office_address',
        'office_telephone_no',
        'office_mobile_no',
        'office_fax_no',
        'office_email',
        'nature_of_business',
        'received_remittance',
        'auth_capital',
        'paid_capital',
        'travel_history',
        'th_visit_with_emp_visa',
        'th_emp_work_permit',
        'th_emp_org_name',
        'th_emp_org_address',
        'th_emp_tin_no',
        'th_emp_wp_no',
        'th_org_post_code',
        'th_org_post_office',
        'th_org_telephone_no',
        'th_org_district_id',
        'th_org_thana_id',
        'th_org_email',
        'th_first_work_permit',
        'th_resignation_letter',
        'th_release_order',
        'th_last_extension',
        'th_last_work_permit',
        'th_income_tax',

        'local_executive',
        'local_stuff',
        'local_total',
        'foreign_executive',
        'foreign_stuff',
        'foreign_total',
        'manpower_total',
        'manpower_local_ratio',
        'manpower_foreign_ratio',

        'arrival_date',
        'arrival_time',
        'arrival_flight_no',
        'departure_date',
        'departure_time',
        'departure_flight_no',
        'visiting_service_id',
        'visa_on_arrival_sought_id',
        'visa_on_arrival_sought_other',
        'airport_id',
        'basic_payment_type_id',
        'basic_local_amount',
        'basic_local_currency_id',
        'basic_foreign_amount',
        'basic_foreign_currency_id',
        'overseas_payment_type_id',
        'overseas_local_amount',
        'overseas_local_currency_id',
        'overseas_foreign_amount',
        'overseas_foreign_currency_id',
        'house_payment_type_id',
        'house_local_amount',
        'house_local_currency_id',
        'house_foreign_amount',
        'house_foreign_currency_id',
        'conveyance_payment_type_id',
        'conveyance_local_amount',
        'conveyance_local_currency_id',
        'conveyance_foreign_amount',
        'conveyance_foreign_currency_id',
        'medical_payment_type_id',
        'medical_local_amount',
        'medical_local_currency_id',
        'medical_foreign_amount',
        'medical_foreign_currency_id',
        'ent_payment_type_id',
        'ent_local_amount',
        'ent_local_currency_id',
        'ent_foreign_amount',
        'ent_foreign_currency_id',
        'bonus_payment_type_id',
        'bonus_local_amount',
        'bonus_local_currency_id',
        'bonus_foreign_amount',
        'bonus_foreign_currency_id',
        'emp_marital_status',
        'emp_spouse_name',
        'emp_spouse_passport_no',
        'emp_spouse_nationality',
        'emp_spouse_work_status ',
        'emp_spouse_org_name ',
        'other_benefits',
        'salary_remarks',
        'auth_name',
        'auth_email',
        'auth_cell_number',
        'shadow_file_path',
        'is_archive',
        'sf_payment_id',
        'gf_payment_id',
        'accept_terms',
        'created_at',
        'created_by',
        'updated_at',
        'updated_by'
    ];

    public static function boot() {
        parent::boot();
        static::creating(function($post) {
            $post->created_by = CommonFunction::getUserId();
            $post->updated_by = CommonFunction::getUserId();
        });

        static::updating(function($post) {
            $post->updated_by = CommonFunction::getUserId();
        });
    }
}
